return {
    -- "nvim-telescope/telescope.nvim",
    -- dependencies = {
    --     "nvim-lua/plenary.nvim",
    --     "joshmedeski/telescope-smart-goto.nvim",
    --     "nvim-telescope/telescope-live-grep-args.nvim",
    -- },
    --
    -- config = function()
    --     local builtin = require("telescope.builtin")
    --     local telescope = require("telescope")
    --     telescope.setup({
    --         defaults = {
    --             vimgrep_arguments = {
    --                 "rg",
    --                 "--no-heading",
    --                 "--with-filename",
    --                 "--line-number",
    --                 "--column",
    --                 "--smart-case",
    --             },
    --         },
    --     })
    --     vim.keymap.set("n", "<leader>ff", builtin.find_files, {})
    --     vim.keymap.set(
    --         "n",
    --         "<leader>fg",
    --         "<cmd>lua require('telescope').extensions.live_grep_args.live_grep_args()<CR>",
    --         { desc = "Live Grep" }
    --     )
    --     vim.keymap.set(
    --         "n",
    --         "<leader>fc",
    --         '<cmd>lua require("telescope.builtin").live_grep({ glob_pattern = "!{spec,test}"})<CR>',
    --         { desc = "Live Grep Code" }
    --     )
    --     vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Find Buffers" })
    --     vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "Find Help Tags" })
    --     vim.keymap.set("n", "<leader>fs", builtin.lsp_document_symbols, { desc = "Find Symbols" })
    --
    --     telescope.load_extension("live_grep_args")
    -- end,
}
