set-option -g default-shell /bin/zsh
set -g prefix ^A
set -g base-index 1
set -g detach-on-destroy off
set -g history-limit 100000000
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top
set -g mouse on

bind r source-file ~/.tmux.conf
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
# bind '\' split-window -h
bind -n C-S-Left resize-pane -L 2
bind -n C-S-Right resize-pane -R 2
bind -n C-S-Up resize-pane -U 2
bind -n C-S-Down resize-pane -D 2

# vim-like pane switching
bind -r ^ last-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "time network-ping"
# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-tmux-ram-usage-colors "dark_purple white"
set -g @dracula-border-contrast true
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

